







	



.build/mega2560/Adafruit-Motor-Shield-library-master/AFMotor.d : lib/Adafruit-Motor-Shield-library-master/AFMotor.cpp
	@mkdir -p .build/mega2560/Adafruit-Motor-Shield-library-master
	@/usr/lib64/ccache/avr-gcc -mmcu=atmega2560 -ffunction-sections -fdata-sections -g -Os -w -DF_CPU=16000000L -DARDUINO=100 -I/usr/share/arduino/hardware/arduino/cores/arduino -I/usr/share/arduino/hardware/arduino/variants/mega -I/usr/share/arduino/hardware/arduino/cores/arduino -Ilib/Adafruit-Motor-Shield-library-master -I/usr/share/arduino/libraries/Servo -I/usr/share/arduino/libraries/LiquidCrystal -I/usr/share/arduino/libraries/SPI -I/usr/share/arduino/libraries/Ethernet -I/usr/share/arduino/libraries/Ethernet/utility -I/usr/share/arduino/libraries/SD -I/usr/share/arduino/libraries/SD/utility -I/usr/share/arduino/libraries/EEPROM -I/usr/share/arduino/libraries/SoftwareSerial -I/usr/share/arduino/libraries/Firmata -I/usr/share/arduino/libraries/Wire -I/usr/share/arduino/libraries/Wire/utility -I/usr/share/arduino/libraries/Stepper  -MM $^ > $@
	
	@printf ".build/mega2560/Adafruit-Motor-Shield-library-master/AFMotor.d .build/mega2560/Adafruit-Motor-Shield-library-master/" | cat - $@ > $@~ && mv $@~ $@



.build/mega2560/Adafruit-Motor-Shield-library-master/dependencies.d : .build/mega2560/Adafruit-Motor-Shield-library-master/AFMotor.d
	@echo [96mScanning dependencies of Adafruit-Motor-Shield-library-master[0m
	@mkdir -p .build/mega2560/Adafruit-Motor-Shield-library-master
	@cat $^ > $@;

all : .build/mega2560/Adafruit-Motor-Shield-library-master/dependencies.d
	@true

